- name: Declare variable at play level
  hosts: all
  connection: local

  vars:
    URL: playlevel.example.com

  tasks:
    - name: access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: access a variable at file level
  hosts: all
  connection: local
  vars_files:
   - var.yml
  tasks:
   - name: Access var from other file
     ansible.builtin.debug:
       msg: URL == {{URL}}



- name: Declare variable at Task level
  hosts: all
  connection: local

  tasks:
    - name : access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: Tasklevel.example.com